### ISSUE TITLE
[feat] dsfrActionButtonCmp - Modal close button refresh

### ISSUE THREAD

**Issue by jeremy-legeay** [pegros/DSFR_LWR#1]
**Is your feature request related to a problem? Please describe.**
When a modal opens, the close button does not refresh the page. For example, if we modify record information in this modal, the modifications are not visible when the modal is closed, and we have to refresh the page manually to see them.

**Describe the solution you'd like**
Enable refresh on the close button.

**Comment by pegros** [comment]
@jeremy-legeay  Is the problem only on the **_dsfrActionButtonCmp_** or also on other button components ?

**Comment by jeremy-legeay** [comment]
The problem is also on other button components.
